FIREFLY_RKMEDIA_UVC_VERSION = 1.0
FIREFLY_RKMEDIA_UVC_SITE_METHOD = local
FIREFLY_RKMEDIA_UVC_SITE = $(TOPDIR)/../app/firefly_rkmedia_uvc/1126
FIREFLY_RKMEDIA_UVC_INSTALL_STAGING = YES 
FIREFLY_RKMEDIA_UVC_INSTALL_TARGET = YES
FIREFLY_RKMEDIA_UVC_DEPENDENCIES += uvc_app rkmedia

ifeq ($(BR2_PACKAGE_FIREFLY_RKMEDIA_UVC),y)
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DCOMPILES_FIREFLY_UVC_EXAMPLE=ON
endif

ifeq ($(BR2_PACKAGE_RKMEDIA_USE_AIQ), y)
FIREFLY_RKMEDIA_UVC_DEPENDENCIES += camera_engine_rkaiq
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DUSE_RKAIQ=ON
endif

ifeq ($(BR2_PACKAGE_DRM_DISPLAY_OUTPUT),y)
FIREFLY_RKMEDIA_UVC_DEPENDENCIES += libdrm
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DDRM_DISPLAY=ON
endif

ifeq ($(BR2_PACKAGE_RKMEDIA_RKRGA),y)
FIREFLY_RKMEDIA_UVC_DEPENDENCIES += linux-rga
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DRKRGA=ON
endif

ifeq ($(BR2_PACKAGE_RKMEDIA_MPP),y)
FIREFLY_RKMEDIA_UVC_DEPENDENCIES += mpp
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DRKMPP=ON \
        -DRKMPP_HEADER_DIR=$(STAGING_DIR)/usr/include/rockchip \
        -DRKMPP_LIB_NAME=rockchip_mpp
endif

ifeq ($(BR2_PACKAGE_RKMEDIA_V4L2_CAPTURE),y)
ifeq ($(BR2_PACKAGE_LIBV4L2),y)
FIREFLY_RKMEDIA_UVC_DEPENDENCIES += libv4l
endif
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DV4L2_CAPTURE=ON
endif

$(eval $(cmake-package))
